12_Django_advanced/cbvs/cbvs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('simple_app/', include('simple_app.urls'))
]

12_Django_advanced/cbvs/simple_app/urls.py
from django.urls import path
from simple_app import views


app_name = "simple_app"

urlpatterns = [
    path("", views.IndexCBV.as_view(), name='homepage'),
    path("list/", views.SchoolListView.as_view(), name='list'),
    path("detail/<int:pk>", views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.StudnetCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.StudentDeleteView.as_view(), name='delete'),
]

12_Django_advanced/cbvs/simple_app/models.py
from django.db import models
from django.urls import reverse


class School(models.Model):
    name = models.CharField(max_length=256)
    city = models.CharField(max_length=50)
    principal = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    school = models.ForeignKey("simple_app.School",
                               related_name='students',
                               on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("simple_app:detail", kwargs={"pk": self.school.pk})

12_Django_advanced/cbvs/simple_app/views.py
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from simple_app import models
from django.urls import reverse_lazy


class IndexCBV(TemplateView):
    template_name = 'simple_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = "Seweryn"
        return context


class SchoolListView(ListView):
    model = models.School
    template_name = "simple_app/list.html"
    context_object_name = 'schools'


class SchoolDetailView(DetailView):
    model = models.School
    template_name = "simple_app/detail.html"
    context_object_name = 'school_detail'


class StudnetCreateView(CreateView):
    model = models.Student
    fields = ['name', 'age', 'school']
    template_name = 'simple_app/create.html'


class StudentUpdateView(UpdateView):
    model = models.Student
    template_name = 'simple_app/create.html'
    fields = ['age', 'school']


class StudentDeleteView(DeleteView):
    model = models.Student
    template_name = 'simple_app/delete.html'
    success_url = reverse_lazy('simple_app:list')

12_Django_advanced/cbvs/simple_app/templates/simple_app/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <nav class="nav justify-content-center">
        <a class="nav-link active" href="{% url 'simple_app:list' %}">List</a>
        <a class="nav-link " href="{% url 'admin:index' %}">Admin</a>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock body_block %}
    </div>
</body>

</html>

12_Django_advanced/cbvs/simple_app/templates/simple_app/create.html
<!doctype html>
<html lang="en">

<head>
    <title>Create a new student</title>
</head>

</html>

{% extends 'simple_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h3>
        {% if not form.instance.pk %}
        Create a new student
        {% else %}
        Edit student info
        {% endif %}
    </h3>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary btn-block" value='Submit!'>
    </form>
</div>

{% endblock body_block %}

12_Django_advanced/cbvs/simple_app/templates/simple_app/delete.html
<!doctype html>
<html lang="en">

<head>
    <title>Welcome</title>
</head>

</html>

{% extends 'simple_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">You're about to delete the following student</h1>
    <hr class="my-2">
    <p>Name: {{ student.name }}</p>
    <p>Age: {{ student.age }}</p>
    <p>School: {{ student.school }}</p>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm" class='btn btn-danger'>
        <a href="{% url 'simple_app:homepage' %}">Return to homepage</a>
    </form>
</div>


{% endblock body_block %}

12_Django_advanced/cbvs/simple_app/templates/simple_app/detail.html
<!doctype html>
<html lang="en">

<head>
    <title>Detailed information</title>
</head>

</html>

{% extends 'simple_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">School Details:</h1>
    <p>Name: {{ school_detail.name }} </p>
    <p>Principal: {{ school_detail.principal }} </p>
    <p>City: {{ school_detail.city }} </p>

</div>
<div class="jumbotron">
    <h2>List of all students</h2>
    <ul>
        {% for student in school_detail.students.all %}
        <li>Name: {{ student.name }} | Age: {{ student.age }}</li>
        {% endfor %}
    </ul>
</div> {% endblock body_block %}

12_Django_advanced/cbvs/simple_app/templates/simple_app/index.html
<!doctype html>
<html lang="en">

<head>
    <title>Welcome</title>
</head>

</html>

{% extends 'simple_app/base.html' %}
{% block body_block %}
<h1>Hi {{ username }}, how are you?</h1>
{% endblock body_block %}

12_Django_advanced/cbvs/simple_app/templates/simple_app/list.html
<!doctype html>
<html lang="en">

<head>
    <title>Listed information</title>
</head>

</html>

{% extends 'simple_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <p class="lead">List of all knows schools:</p>
    <ol>
        {% for school in schools %}
        <li><a href="{% url "simple_app:detail" pk=school.id %}">{{ school.name }}</a></li>
        {% endfor %}
    </ol>
</div>

{% endblock body_block %}