11_Django/first_project/first_app/urls.py
from django.urls import path
from first_app import views


app_name = "first_app"

urlpatterns = [
    path("", views.nested, name='home_page'),
    path("img", views.image),
    path("webpages", views.webpages),
    path("form", views.form, name='register'),
    path("users", views.users, name='users'),
    path("login", views.login_user, name='login'),
    path("logout", views.logout_user, name='logout')
]

11_Django/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

11_Django/first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    topic_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.topic_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(max_length=200)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class ExtendedUser(models.Model):
    # instead of creating a new User model you can
    # just extend the built in version
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics",
                                    height_field=None,
                                    width_field=None,
                                    max_length=None,
                                    blank=True)

    def __str__(self):
        return self.user.username

11_Django/first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import ExtendedUser
from django.contrib.auth.models import User


def custom_validator(value):
    if any(i.isdigit() for i in value):
        raise forms.ValidationError("Name should not contain digits!")
    return value


class NewUserForm(forms.ModelForm):
    username = forms.CharField(validators=[custom_validator])
    email = forms.EmailField()
    email_valid = forms.EmailField(label="Email again:")
    # empty form field used to counter brainless bots
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])
    password = forms.CharField(widget=forms.PasswordInput)

    # validate all values at once
    def clean(self):
        form = super().clean()

        if form['email'] != form['email_valid']:
            raise forms.ValidationError("Emails dont match >:-(")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    field_order = ['username', 'password', 'email', 'email_valid']


class ExtendedUserForm(forms.ModelForm):
    class Meta():
        model = ExtendedUser
        fields = ["profile_pic"]


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

11_Django/first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import Webpage, ExtendedUser
from first_app.forms import NewUserForm, ExtendedUserForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return HttpResponse("<h1>Hello there<h1>")


def nested(request):
    context = {"insert_me": "Ah welcome from views.py"}
    return render(request, "first_app/index.html", context=context)


def image(request):
    return render(request, "first_app/pic.html")


def webpages(request):
    webpages = Webpage.objects.order_by("name")
    context = {"webpages": webpages}
    return render(request, "first_app/webpages.html", context=context)


def form(request):

    registered = False

    if request.method == "POST":
        user_form = NewUserForm(request.POST)
        extra_form = ExtendedUserForm(request.POST)

        if user_form.is_valid() and extra_form.is_valid():
            # add the new user to the list
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            ext_user = extra_form.save(commit=False)
            ext_user.user = user

            if 'profile_pic' in request.FILES:
                ext_user.profile_pic = request.FILES['profile_pic']

            ext_user.save()

            registered = True

    context = {"user_form": NewUserForm(),
               "extra_form": ExtendedUserForm(),
               "registered": registered}

    return render(request, "first_app/form_page.html", context=context)


def users(request):
    users_list = ExtendedUser.objects.all()
    context = {"users_list": users_list}
    return render(request, "first_app/users.html", context=context)


def login_user(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect(reverse('home_page'))

    context = {"form": LoginForm()}
    return render(request, "first_app/login.html", context=context)


@login_required
def logout_user(request):
    logout(request)
    return HttpResponse("<h2>Logged out<h2>")

11_Django/first_project/first_app/templates/first_app/base.html
<!doctype html>
<html lang="en">

<head>
    <title>L</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'first_app:home_page' %}">HOMEPAGE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'first_app:register' %}">REGISTER</a>
            </li>
        </ul>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock body_block %}
    </div>
</body>

</html>

11_Django/first_project/first_app/templates/first_app/form_page.html
<!doctype html>

<html>

<head>
    <title>Register!</title>
</head>

</html>

{% extends 'first_app/base.html' %}
{% block body_block %}
<div class="container">
    <a href="{% url 'first_app:users' %}">All registered users</a>
</div>
<div class="container">
    <div class="jumbotron">

        {% if registered %}

        <p>You're registerd!</p>

        {% else %}

        <form method="POST" enctype='multipart/form-data'>
            {{ user_form.as_p }}
            {{ extra_form.as_p}}
            {% csrf_token %}
            <input type="Submit" class="btn btn-primary" value='Submit!'>
        </form>

        {% endif %}
    </div>
</div>
{% endblock body_block %}

11_Django/first_project/first_app/templates/first_app/index.html
<!doctype html>

<html>

<head>
    <title>First app homepage!</title>
</head>

</html>

{% extends 'first_app/base.html' %}
{% block body_block %}
<h1>This is index.html</h1>
{{insert_me}}
{% endblock body_block %}

11_Django/first_project/first_app/templates/first_app/login.html
<html>

<head>
    <title>Log in!</title>
</head>

<head>
    <html>
    {% extends 'first_app/base.html' %}
    {% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">Log in!</h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
    {% endblock %}

11_Django/first_project/first_app/templates/first_app/pic.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "css/coolstyle.css" %}">
    <title>Picture</title>
</head>

<body>
    <h1>Wow look at this cool pic</h1>
    <img src="{% static "images/django.png" %}" alt='File missing ;('>
</body>

</html>

11_Django/first_project/first_app/templates/first_app/users.html
<!doctype html>

<html>

<head>
    <title>List of all registered users</title>
</head>

</html>
{% extends 'first_app/base.html' %}
{% load static %}
{% block body_block %}

<div class="container">
    <h1>List of all registered users:</h1>
    {% if users_list %}
    <table class="table">
        <thead class='thead-dark'>
            <tr>
                <th>Picture</th>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users_list %}
            <tr>
                <td>{% if user.profile_pic %}
                    <img src={{ user.profile_pic.url }} width="100" height="100">
                    {% endif %}</td>
                <td>{{ user.user.username }}</td>
                <td>{{ user.user.email }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No registered users yet!</p>
    {% endif %}
</div>
</body>
{% endblock %}

11_Django/first_project/first_app/templates/first_app/webpages.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "css/coolstyle.css" %}">
    <title>Webpages</title>

</head>

<body>
    <h1>List of known webpages</h1>

    {% if webpages %}
    <table>
        <tr>
            <th>Name</th>
            <th>Topic</th>
            <th>Url</th>
        </tr>

        {% for webpage in webpages %}
        <tr>
            <td>{{ webpage.name }}</td>
            <td>{{ webpage.topic }}</td>
            <td>{{ webpage.url }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <p>No webpages found!</p>
    </table>
    {% endif %}
</body>

</html>

11_Django/first_project/templates/first_app/form_page.html
<!doctype html>

<html>

<head>
    <title>Register!</title>
</head>

</html>

{% extends 'first_app/base.html' %}
{% block body_block %}
<div class="container">
    <a href="{% url 'first_app:users' %}">All registered users</a>
</div>
<div class="container">
    <div class="jumbotron">
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="Submit" class="btn btn-primary" value='Submit!'>
        </form>
    </div>
</div>
{% endblock body_block %}

11_Django/first_project/templates/first_app/users.html
<!doctype html>

<html>

<head>
    <title>List of all registered users</title>
</head>

</html>

{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="container">
    <h1>List of all registered users:</h1>
    {% if users_list %}
    <table class="table">
        <thead class='thead-dark'>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users_list %}
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No registered users yet!</p>
    {% endif %}
</div>
</body>
{% endblock %}