13_Blog_project/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

13_Blog_project/blog/posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"

urlpatterns = [
    path("", views.IndexView.as_view(), name='homepage'),
    path("new", views.NewPostView.as_view(), name='new_post'),
    path("drafts", views.DraftView.as_view(), name='drafts'),
    path("drafts/<slug>/edit", views.UpdateDraft.as_view(), name='edit_draft'),
    path("drafts/<slug>/publish", views.PublishDraft.as_view(), name='publish'),
    path("drafts/<slug>/delete", views.DeleteDraft.as_view(), name='delete'),
    path("read/<slug>", views.PostView.as_view(), name='post'),
]

13_Blog_project/blog/registration/urls.py
from django.urls import path
from registration import views


app_name = "registration"


urlpatterns = [
    path("register/", views.RegisterView.as_view(), name='register'),
    path("login/", views.LoginView.as_view(), name='login'),
    path("logout/", views.LogoutView.as_view(), name='logout'),
    path("p/<slug>", views.ProfileView.as_view(), name='profile'),
]

13_Blog_project/blog/posts/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse


class Post(models.Model):
    title = models.CharField(max_length=64)
    text = models.TextField()
    draft = models.BooleanField(default=True)
    date_published = models.DateTimeField(auto_now=True)
    author = models.ForeignKey("registration.Author",
                               on_delete=models.CASCADE)
    text_preview = models.TextField(default=" ")
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.text_preview = self.text[:500]
        self.slug = slugify(self.title[:20] + "-" + str(self.author.user.id))
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:drafts")


class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey("registration.Author",
                               on_delete=models.CASCADE)
    post = models.ForeignKey("posts.Post",
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:100]

13_Blog_project/blog/posts/forms.py
from django import forms
from posts import models


class CommentForm(forms.ModelForm):
    text = forms.CharField(max_length=1000, required=True, label="",
                           widget=forms.Textarea)

    class Meta:
        model = models.Comment
        fields = ['text']


class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=128, required=True, label="",
                            widget=forms.HiddenInput(attrs={'id': 'actual_title'}))
    text = forms.CharField(required=True, label="",
                           widget=forms.HiddenInput(attrs={'id': 'actual_text'}))

    class Meta:
        model = models.Post
        fields = ['title', 'text']

13_Blog_project/blog/posts/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from posts import models
from django.shortcuts import redirect, render
from django.http import HttpResponseNotFound
from datetime import datetime
from posts import forms


class IndexView(ListView):
    template_name = "posts/index.html"
    model = models.Post
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.model.objects.filter(draft=False).order_by('-date_published')
        return query


class NewPostView(CreateView):
    template_name = "posts/view_post.html"
    model = models.Post
    form_class = forms.PostForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['creating'] = True
        return context

    def form_valid(self, form):
        title = form.cleaned_data['title']
        text = form.cleaned_data['text']
        author = self.request.user.author
        draft = True

        post = models.Post(title=title, text=text,
                           author=author, draft=draft)

        post.save()
        return redirect("posts:drafts")


class DraftView(ListView):
    template_name = 'posts/drafts.html'
    model = models.Post
    context_object_name = "posts"

    def get_queryset(self):
        author = self.request.user.author
        query = self.model.objects.filter(author=author, draft=True)
        return query


class UpdateDraft(UpdateView):
    model = models.Post
    template_name = 'posts/view_post.html'
    form_class = forms.PostForm

    def get_context_data(self, *args, **kwargs):
        context = super(UpdateDraft, self).get_context_data(*args, **kwargs)
        context['editing'] = True
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.author != self.get_object().author:
            return HttpResponseNotFound()
        return super().dispatch(request, *args, **kwargs)


class PublishDraft(DetailView):
    model = models.Post
    template_name = "posts/view_post.html"
    context_object_name = "post"

    def dispatch(self, request, *args, **kwargs):
        if request.user.author != self.get_object().author:
            return HttpResponseNotFound()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['publishing'] = True
        return context

    def post(self, request, slug):
        post = self.get_object()
        post.draft = False
        post.date_published = datetime.now()
        post.save()
        return redirect("/")


class DeleteDraft(DeleteView):
    model = models.Post
    template_name = "posts/view_post.html"
    context_object_name = "post"
    success_url = "/drafts"

    def dispatch(self, request, *args, **kwargs):
        if request.user.author != self.get_object().author:
            return HttpResponseNotFound()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['deleting'] = True
        return context


class PostView(DetailView):
    model = models.Post
    template_name = "posts/view_post.html"
    context_object_name = "post"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['new_comment_form'] = forms.CommentForm()
        comments = models.Comment.objects.filter(post=self.get_object())
        context['comments'] = comments
        context['num_comments'] = len(comments)
        return context

    def post(self, request, slug):
        comment_form = forms.CommentForm(request.POST)
        if comment_form.is_valid():
            text = comment_form.cleaned_data['text']
            author = self.request.user.author
            post = self.get_object()
            comment = models.Comment(text=text, author=author, post=post)
            comment.save()
            return redirect("posts:post", slug=slug)
        else:  # if form is invalid
            errors = []
            for message in comment_form.errors.values():
                errors.append(message)
            context = self.get_context_data()
            context['comment_form_errors'] = errors
            return render(request, self.template_name, context=context, slug=slug)

13_Blog_project/blog/posts/templates/posts/drafts.html
{% extends 'navbar.html' %}
{% block title %}Drafts{% endblock title %}

{% block body_block %}
<div class="container">

    <h2>Your unpublished drafts:</h2>
    {% if posts %}
    {% for post in posts %}
    <div class="alert alert-light" role="alert">
        <span class='draft_name'>{{post.title}}</span>
        <span class='buttons_on_right'>
            <a class="btn btn-primary" href="{% url 'posts:edit_draft' slug=post.slug %}">Edit</a>
            <a class="btn btn-primary" href="{% url 'posts:publish' slug=post.slug %}">Publish</a>
            <a class="btn btn-danger" href="{% url 'posts:delete' slug=post.slug %}">Delete</a>
        </span>
    </div>
    {% endfor %}
    {% else %}
    <p>Nothing to see here, <a href="{% url 'posts:new_post' %}">create a new one!</a></p>
    {% endif %}
</div>
{% endblock body_block%}

13_Blog_project/blog/posts/templates/posts/edit_post.html
{% extends 'navbar.html' %}
{% block title %}Edit your post{% endblock title %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Edit the post</h1>
        <hr class="my-2">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <input type="submit" class="btn btn-primary" value='Save as draft'>
        </form>
    </div>
</div>
{% endblock body_block%}

13_Blog_project/blog/posts/templates/posts/index.html
{% extends 'navbar.html' %}
{% block title %}Welcome to my blog!{% endblock title %}

{% block body_block %}
<div class="container">
    <h2 class='animated_text display-2'>Newest posts:</h2>
    {% for post in posts %}
    <div class="jumbotron">
        <h1 class='post_title' id='fake_title'>{{post.title}}</h1>
        <p class="lead">
            by
            <a href="{% url 'registration:profile' slug=post.author.slug%}">
                {{post.author.user.username}}</a>
            published on <span class='date-style'>{{post.date_published}}</span>
        </p>
        <hr class="my-2">
        <div class='post_text' id='fake_text'>{{post.text_preview}}</div>
        <p>...</p>
        <a class="btn btn-outline-secondary" href="{% url 'posts:post' slug=post.slug%}" role="button">Read more</a>
    </div>
    {% endfor %}
</div>
{% endblock body_block %}

13_Blog_project/blog/posts/templates/posts/preview_post.html
{% extends 'navbar.html' %}
{% block title %}{{ post.title }}{% endblock title %}

{% block body_block %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {% if publish %}
        <div class="alert alert-success" role="alert">
            <strong>You're about to publish this post </strong>
            <input type="submit" value="Confirm" class='btn btn-outline-success'>
            <a href="{% url 'posts:drafts' %}" class='btn btn-outline-primary'>Cancel</a>
        </div>
        {% elif delete %}
        <div class="alert alert-danger" role="alert">
            <strong>You're about to delete this post </strong>
            <input type="submit" value="Confirm" class='btn btn-outline-danger'>
            <a href="{% url 'posts:drafts' %}" class='btn btn-outline-primary'>Cancel</a>
        </div>
        {% endif %}
    </form>
    <h1>{{post.title}}</h1>
    <hr class="my-2">
    <h6>
        by
        <img src={{ post.author.profile_pic.url }} width="40" height="40" alt="" class='rounded-lg'>
        <a href="{% url 'registration:profile' slug=post.author.slug%}">
            {{post.author.user.username}}</a>
        published on <span class='date-style'>{{post.date_published}}</span>
    </h6>
    <hr class="my-2">
    <p>{{post.text|linebreaks}}</p>
    <div class="jumbotron">
        <h3>
            Comments(
            {% if num_comments %}
            {{ num_comments }}
            {% else %}
            0
            {% endif %}
            )
        </h3>
        {% if comment_form_errors %}
        <div class="alert alert-danger" role="alert">
            Incorrect data provided!
            {% for error in errors%}
            <p>{{error}}</p>
            {% endfor %}
        </div>
        {% endif %}
        {% if not publish and not delete %}
        <hr class="my-2">
        <form method="post" class="comment_form">
            {{new_comment_form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value='Publish!'>
        </form>
        <ul class='comments_list'>
            {% for comment in comments %}
            <li>
                <img src={{ comment.author.profile_pic.url }} width="40" height="40" alt="" class='rounded-lg'>
                <a href="{% url 'registration:profile' slug=comment.author.slug%}">
                    {{comment.author.user.username}}</a>:
                <span class='comment_text'>
                    {{comment.text}}
                </span>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock body_block %}

13_Blog_project/blog/posts/templates/posts/view_post.html
{% extends 'navbar.html' %}
{% block title %}Create a new post{% endblock title %}

{% block body_block %}
<div class="jumbotron">
    {% if creating %}
    <h1>Create a new post</h1>

    {% elif editing %}
    <h1>Edit your post</h1>

    {% elif publishing %}
    <form method="post">
        {% csrf_token %}
        <div class="alert alert-success" role="alert">
            <strong>You're about to publish this post </strong>
            <input type="submit" value="Confirm" class='btn btn-outline-success'>
            <a href="{% url 'posts:drafts' %}" class='btn btn-outline-primary'>Cancel</a>
        </div>
    </form>
    {% elif deleting %}
    <form method="post">
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            <strong>You're about to delete this post </strong>
            <input type="submit" value="Confirm" class='btn btn-outline-danger'>
            <a href="{% url 'posts:drafts' %}" class='btn btn-outline-primary'>Cancel</a>
        </div>
    </form>
    {% endif %}
    <hr class="my-2">
    {% if creating or editing %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <div contenteditable="true" class="custom_textarea" id="fake_title">{{post.title}}</div>
        <div contenteditable="true" class="custom_textarea" id="fake_text">{{post.text|linebreaks}}</div>
        <input type="submit" class="btn btn-primary" id="save_draft_btn" value='Save as draft'>
    </form>
    {% else %}
    <h1 class='post_title' id="fake_title">{{post.title}}</h1>
    <hr class="my-2">
    <h6>
        by
        <img src={{ post.author.profile_pic.url }} width="40" height="40" alt="" class='rounded-lg'>
        <a href="{% url 'registration:profile' slug=post.author.slug%}">
            {{post.author.user.username}}</a>
        published on <span class='date-style'>{{post.date_published}}</span>
    </h6>
    <hr class="my-2">
    <div class='post_text' id="fake_text">
        {{post.text|linebreaks}}
    </div>
    {% endif %}
    {% if not creating and not publishing and not deleting and not editing %}
    <div class="jumbotron">
        <h3>
            Comments(
            {% if num_comments %}
            {{ num_comments }}
            {% else %}
            0
            {% endif %}
            )
        </h3>
        {% if comment_form_errors %}
        <div class="alert alert-danger" role="alert">
            Incorrect data provided!
            {% for error in errors%}
            <p>{{error}}</p>
            {% endfor %}
        </div>
        {% endif %}
        <hr class="my-2">
        <form method="post" class="comment_form">
            {{new_comment_form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value='Publish!'>
        </form>
        <ul class='comments_list'>
            {% for comment in comments %}
            <li>
                <img src={{ comment.author.profile_pic.url }} width="40" height="40" alt="" class='rounded-lg'>
                <a href="{% url 'registration:profile' slug=comment.author.slug%}">
                    {{comment.author.user.username}}</a>:
                <span class='comment_text'>
                    {{comment.text}}
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
<div class="toast" data-autohide="false">
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"> <span
            aria-hidden="true">&times;</span>
    </button>
    <div class="toast-body">
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-secondary" id='make_text_bold'> <b>bold</b> </button>
            <button type="button" class="btn btn-secondary" id='make_text_italic'><I>italic</I></button>
            <button type="button" class="btn btn-secondary" id='make_text_strike'><strike>strike</strike></button>
            <button type="button" class="btn btn-secondary" id='make_text_clear'>clear</button>
        </div>
    </div>
</div>
{% endblock body_block%}

13_Blog_project/blog/templates/navbar.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <title>{% block title %}{% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% comment %} BOOTSTRAP {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% comment %} FONTS {% endcomment %}
    <link href="https://fonts.googleapis.com/css?family=Abel|Cinzel|Grenze|Libre+Caslon+Display&display=swap"
        rel="stylesheet">
    {% comment %} STYLESHEETS {% endcomment %}
    <link rel="stylesheet" href="{% static "css/indexstyle.css" %}">
    <link rel="stylesheet" href="{% static "css/navbarstyle.css" %}">
    <link rel="stylesheet" href="{% static "css/richstyle.css" %}">
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link navbar-brand" id="HOMEPAGE" href="{% url 'posts:homepage' %}">Homepage</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-coolfont" href="https://github.com/SewerynKras/">GitHub</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-coolfont" href="https://www.linkedin.com/in/sewerynkras/">Linkedin</a>
            </li>
        </ul>
        <ul class='nav navbar-nav ml-auto'>
            {% if user.is_authenticated %}
            <li>
                <span class='navbar-text navbar-coolfont'>
                    Hello <span class="text-primary">{{ user.username }}</span>
                </span>
            </li>
            <li>
                <a class='nav-link navbar-coolfont' href="{% url 'registration:profile' slug=user.author.slug%}">My
                    profile</a>
            </li>
            <li>
                <a class='nav-link navbar-coolfont' href="{% url 'posts:drafts' %}">Drafts</a>
            </li>
            <li>
                <a class='nav-link navbar-coolfont' href="{% url 'posts:new_post' %}">New post</a>
            </li>
            <li>
                <a class='nav-link navbar-coolfont' href="{% url 'registration:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <a class='nav-link navbar-coolfont' href="{% url 'registration:login' %}">Log in</a>
            </li>
            <a class='nav-link navbar-coolfont' href="{% url 'registration:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock body_block %}
    </div>

</body>
<script src="{% static "scripts/rich_editor.js" %}"></script>

</html>